baseURL = "http://blog.ylitalot.com/"
copyright = "Juha Ylitalo &lt;juha@ylitalot.net&gt;"
languageCode = "en-us"
title = "(Dev)Ops observations"
theme = "ananke"
[params]
  description = "Observations from working in public cloud environments"
  twitter = "https://twitter.com/jylitalo"
