baseURL = "http://blog.ylitalot.com/"
title = "(Dev)Ops observations"
copyright = "Juha Ylitalo &lt;juha@ylitalot.net&gt;"

hasCJKLanguage = false
languageCode = "en"

theme = "hugo-theme-jane"
paginate = 3
PygmentsCodeFences = true
PygmentsUseClasses = true
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

[params]
  description = "Observations from working in public cloud environments"
  twitter = "https://twitter.com/jylitalo"
  mainSections = ["post"]

[params.social]
  a-email = "mailto:juha.ylitalo@gmail.com"
  c-twitter = "https://twitter.com/jylitalo"
  g-github = "https://github.com/jylitalo"
